"""The search set-up: interleaved evaluation split, HVAC schedule, pinned parameters, two-stage fitting."""

import numpy as np
import pandas as pd
import pytest
import torch

from rcmodel import (
    RC_PARAM_KEYS,
    build_pbt_scheduler,
    fit_free_float,
    free_float_mask,
    interleaved_blocks,
    make_dataloaders,
    model_creator,
    narrow_ranges,
    pinned_parameters,
    search_space,
    write_weather_csv,
)
from rcmodel.optimisation.pbt import physical_to_scaled, sample_plausible_population

# --------------------------------------------------------------------------- interleaved evaluation split


def _row_index(csv_path):
    times = pd.read_csv(csv_path, usecols=[1]).iloc[:, 0].to_numpy()
    return {t: i for i, t in enumerate(times)}


def test_interleaved_split_holds_out_every_kth_block_and_training_never_overlaps(data_config):
    size = 20
    config = {**data_config, "sample_size": size, "eval_split": {"mode": "interleaved", "every": 3}}
    train, evaluation = make_dataloaders(config)
    rows = _row_index(data_config["csv_path"])
    blocks = interleaved_blocks(len(rows), size, 3)
    assert blocks[:3] == [2, 5, 8]

    held_out = set()
    assert len(evaluation) == len(blocks)
    for (t, _), block in zip(evaluation, blocks, strict=True):
        first = rows[t.flatten()[0].item()]
        assert first == block * size and len(t.flatten()) == size
        held_out.update(range(first, first + size))

    dataset = train.dataset
    for _ in range(300):  # random windows
        t, _ = dataset[0]
        window = {rows[x] for x in t.numpy()}
        assert not window & held_out, "a training window overlaps a held-out evaluation block"

    history_t, _ = evaluation.dataset.get_history()
    assert len(history_t) == (max(blocks) + 1) * size


def test_tail_split_is_unchanged(data_config):
    train, evaluation = make_dataloaders(data_config)
    assert evaluation.dataset.block_indices is None
    assert train.dataset.exclude_blocks == []


# --------------------------------------------------------------------------- schedule


def test_free_float_mask_follows_the_schedule():
    schedule = {"weekdays": [0, 1, 2, 3, 4], "start": "07:00", "end": "19:00"}
    times = pd.to_datetime(
        ["2023-05-01 06:59", "2023-05-01 07:00", "2023-05-01 18:59", "2023-05-01 19:00", "2023-05-06 12:00"]
    )  # Monday x4, Saturday
    unix = (times - pd.Timestamp("1970-01-01")).total_seconds().to_numpy()
    np.testing.assert_array_equal(free_float_mask(unix, schedule), [True, False, False, True, True])
    # Local time an hour ahead of UTC: 06:00 UTC is 07:00 local, available.
    shifted = free_float_mask(unix[:1] - 59 * 60 + 0, {**schedule, "utc_offset_hours": 1})
    assert not shifted[0]


# --------------------------------------------------------------------------- pinned parameters


def test_pinned_parameters_are_constants_and_never_mutated(get_model_config):
    config = {**get_model_config, "gain": [2.0, 2.0]}
    pinned = pinned_parameters(config)
    assert pinned["gain"] == 2.0
    assert {"C_rm_mass", "R_rm_mass", "T_set"} <= set(pinned)  # optional keys, pinned at [0, 0]
    space = search_space(config)
    assert space["gain"] == 2.0
    scheduler = build_pbt_scheduler(config)
    assert not set(pinned) & set(scheduler._hyperparam_mutations)
    population = sample_plausible_population(config, 3, max_time_constant_days=1e6)
    assert all(member["gain"] == 2.0 for member in population)


def test_rin_is_pinned_for_a_single_room(get_model_config):
    one_room = {**get_model_config, "room_names": ["a"], "room_coordinates": [[[0, 0], [5, 0], [5, 5], [0, 5]]]}
    assert pinned_parameters(one_room)["Rin"] == one_room["Rin"][0]
    assert "Rin" not in pinned_parameters(get_model_config)


# --------------------------------------------------------------------------- two-stage fitting

TRUTH = {
    "C_rm": 3e4,
    "C1": 2e7,
    "C2": 1e7,
    "R1": 0.15,
    "R2": 1.3,
    "R3": 0.3,
    "Rin": 1.0,
    "k_sa": 1.0,
    "cool": 0.0,
    "gain": 1.0,
    "solar": 0.0,
}


@pytest.fixture
def synthetic_one_room(tmp_path):
    """Eight days of one room's temperature generated by the model itself, with sun and a daily cycle.

    Simulated from a 10-day spin-up so the record starts on its periodic cycle, as real data does:
    the envelope's latent nodes are then recoverable from the history (get_iv_array's steady-state
    first guess is close), where a record starting far from equilibrium would need several of the
    envelope's ~3-day time constants to settle.
    """
    dt = 600
    spin_up = 10 * 86_400 // dt
    time = 1_683_000_000 + np.arange(0, 18 * 86_400, dt, dtype=np.float64)
    hours = (time - time[0]) / 3600
    tout = 12 + 6 * np.sin(2 * np.pi * (hours - 9) / 24)
    ghi = np.clip(800 * np.sin(2 * np.pi * (hours - 6) / 24), 0, None)
    weather = write_weather_csv(tmp_path / "weather.csv", time, tout, ghi)
    config = {
        "C_rm": [1e3, 1e5],
        "C1": [1e5, 1e8],
        "C2": [1e5, 1e8],
        "R1": [0.05, 5],
        "R2": [0.1, 5],
        "R3": [0.1, 6],
        "Rin": [0.1, 5],
        "k_sa": [0, 3],
        "cool": [0, 50],
        "gain": [0, 5],
        "solar": [0, 0.05],
        "room_names": ["room"],
        "room_coordinates": [[[0, 0], [10, 0], [10, 8], [0, 8]]],
        "room_height": 3.0,
        "weather_csv": str(weather),
        "cooling_policy": None,
        "hvac_schedule": {"weekdays": [], "start": "07:00", "end": "19:00"},  # never available: all free-float
    }
    model = model_creator({**config, "parameters": physical_to_scaled(config, TRUTH)})
    model.setup()
    model.iv = torch.tensor([[16.0], [18.0], [20.0]])
    rooms = model(torch.tensor(time), action=0).squeeze(-1)[:, 2].numpy()
    time, rooms = time[spin_up:], rooms[spin_up:]
    csv = tmp_path / "room_sorted.csv"
    pd.DataFrame({"date-time": pd.to_datetime(time, unit="s"), "time": time, "room": rooms}).to_csv(csv, index=False)
    data_config = {"csv_path": str(csv), "sample_size": 72 * 6, "warmup_size": 0, "dt": dt}
    return config, data_config


def test_fit_free_float_recovers_the_parameters_that_made_the_data(synthetic_one_room):
    config, data_config = synthetic_one_room
    start = {**TRUTH, "R2": TRUTH["R2"] * 1.4, "C_rm": TRUTH["C_rm"] * 0.6}
    fit = fit_free_float(config, data_config, keys=["R2", "C_rm"], start=start, maxfev=300)
    assert fit["n_segments"] >= 1 and fit["rmse"] < 0.02
    assert fit["physical"]["R2"] == pytest.approx(TRUTH["R2"], rel=0.03)
    assert fit["physical"]["C_rm"] == pytest.approx(TRUTH["C_rm"], rel=0.03)
    assert fit["physical"]["C1"] == TRUTH["C1"]  # not fitted: held at its start value


def test_fit_free_float_needs_a_schedule(synthetic_one_room):
    config, data_config = synthetic_one_room
    with pytest.raises(ValueError, match="hvac_schedule"):
        fit_free_float({k: v for k, v in config.items() if k != "hvac_schedule"}, data_config)


def test_narrow_ranges_recentres_the_search():
    config = {key: [0.1, 10.0] for key in RC_PARAM_KEYS}
    config["gain"] = [1.0, 1.0]  # pinned stays pinned
    narrowed = narrow_ranges(config, {"R1": 2.0, "gain": 5.0, "cool": 0.0}, factor=2.0)
    assert narrowed["R1"] == [1.0, 4.0]
    assert narrowed["gain"] == [1.0, 1.0]
    assert narrowed["cool"] == [0.1, 10.0]  # a zero can't be scaled by a factor: left alone
